telegram-bot:
  token: 1754403412:AAFQ5cO26nf8emGj0EkSfAmyS5PCqMNdm90
  name: '@karabin_test_bot'
app:
  maxHours: 16
  minHours: 2
  defaultMessage: Сначала напиши ТЗ
  percentForClean: 10
server:
  port: '8081'
logging:
  file:
    name: '/var/log/viSauna.log'

  level:
    org:
      springframework:
        web: WARN

  pattern:
    file: "%d{DEFAULT} %-5p level %c{1.1.~.~} - %msg %throwable{10}%n"